new: [UI] Download GPG public key from GPG homedir
MISP/MISP pull request #5234
Opened 2019-09-27 16:52 UTC by JakubOnderka

## What does it do?

Currently the GPG public key is stored in two locations: GPG homedir and `app/webroot/gpg.asc`. So for example if admin update key just in GPG homedir, users will still download old/expired key. 

This pull request introduce new config `MISP.download_gpg_from_homedir` and when this config is set to `true`, public key will be extracted and downloaded from GPG homedir.

## Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

## Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

2019-11-08 12:56 UTC, adulau requested changes
Thanks a lot. It's a good one but I see an issue if you fetch a key with a similar key id (email) in the same key ring. Maybe adding the ability to force a specific fingerprint?

2019-11-11 08:14 UTC, JakubOnderka commented
@adulau Thats true, but the logic is the same when signing e-mails during sending: https://github.com/MISP/MISP/blob/2eda47f21835037e9e2671ac8e4ba5124eee1c9d/app/Model/User.php#L909

So I can change the behaviour, but then it must be changed also in User model.

2019-11-11 08:22 UTC, iglocska commented
I think the problem is somewhat different - I can see separate keys being generated for the instance (info@myorg.org for example) in an automated fashion and landing on the same host's public keyring. Not sure how much of an issue this really is.

For users it's less of an issue.

2019-12-13 17:31 UTC, JakubOnderka commented
@iglocska @adulau  Sorry, I still don't understand. 

The way is the same as for choosing key for signing e-mails – just by e-mail address. So if there is problem with key choosing for this change (public key download), the same problem is here already for signing e-mails.

2020-12-17 12:44 UTC, merged